DATA_ROOT = ""

class FileNames:
    """Centralized file naming constants organized by directory structure."""
    class Raw:
        """Raw input files, saved after running initial validation checks."""
        TAXPAYER_RECORDS_RAW: str = "taxpayer_records"
        CORPS_RAW: str = "corps"
        LLCS_RAW: str = "llcs"
        CLASS_CODE_DESCRIPTIONS: str = "class_code_descriptions"
        BLDG_CLASS_CODES_RAW: str = "bldg_class_codes"

    class Analysis:
        """Analysis files generated by the workflow and used for manual research & input."""
        FREQUENT_TAX_NAMES: str = "frequent_tax_names"
        FREQUENT_ADDRS: str = "frequent_tax_addrs"
        FIXING_TAX_NAMES: str = "fixing_tax_names"
        FIXING_ADDRS: str = "fixing_tax_addrs"
        ADDRESS_ANALYSIS: str = "address_analysis"

    class Processed:
        """Datasets generated by different stages of the workflow."""
        TAXPAYER_RECORDS_CLEAN: str = "taxpayer_records"
        CORPS_CLEAN: str = "corps"
        LLCS_CLEAN: str = "llcs"
        BLDG_CLASS_CODES_CLEAN: str = "bldg_class_codes"
        VALIDATED_ADDRS: str = "validated_addrs"
        UNVALIDATED_ADDRS: str = "unvalidated_addrs"
        PROPS_PREPPED: str = "props_prepped"
        PROPS_STRING_MATCHED: str = "props_string_matched"
        PROPS_NETWORKED: str = "props_networked"

    class SummaryStats:
        """Summary statistics for each stage of the workflow."""
        pass

    class FinalOutputs:
        """Final datasets."""
        pass
