from opndb.types.base import WorkflowConfigs


class Dirs:
    """Directory names for workflow data file storage, corresponding to classes."""
    PRE_PROCESS = "pre_process"
    RAW: str = "raw"
    GEOCODIO: str = "geocodio"
    GCD_PARTIALS: str = "partials"
    ANALYSIS: str = "analysis"
    PROCESSED: str = "processed"
    SUMMARY_STATS: str = "summary_stats"
    OUTPUT: str = "output"
    VALIDATION_ERRORS: str = "validation_errors"

class FileNames:
    """Centralized file naming constants organized by directory structure."""
    @classmethod
    def get_raw_filename_ext(cls, filename: str, config: WorkflowConfigs) -> str:
        """Sets file extension on file names. Allows for flexibility in file format of data inputs"""
        return f"{filename}.{config['load_ext']}"

class Root(FileNames):
    CONFIGS: str = "configs.json"

class PreProcess(FileNames):
    TAXPAYERS_CITY: str = "Assessing_Department_Parcel_Data_2024"
    TAXPAYERS_COUNTY: str = "County_Parcels"
    BUSINESS_FILINGS_1: str = "mnsosdat_type1"
    BUSINESS_FILINGS_3: str = "mnsosdat_type3"
    RENTAL_LICENSES: str = "Active_Rental_Licenses"
    PROPS_ADDRESSES: str = "Address_Points"

class Raw(FileNames):
    """Raw input files, saved after running initial validation checks."""
    PROPS_TAXPAYERS: str = "props_taxpayers"
    PROPS_ADDRESSES: str = "props_addresses"
    CORPS: str = "corps"
    LLCS: str = "llcs"
    CLASS_CODES: str = "class_codes"
    BUS_FILINGS: str = "bus_filings"
    BUS_NAMES_ADDRS: str = "bus_names_addrs"

class Geocodio(FileNames):
    GCD_VALIDATED: str = "gcd_validated"
    GCD_UNVALIDATED: str = "gcd_unvalidated"
    GCD_FAILED: str = "gcd_failed"
    GCD_STRING_MATCH: str = "gcd_string_match"

class Analysis(FileNames):
    """Analysis files generated by the workflow and used for manual research & input."""
    FREQUENT_TAX_NAMES: str = "frequent_tax_names"
    FIXING_TAX_NAMES: str = "fixing_tax_names"
    FIXING_ADDRS: str = "fixing_addrs"
    FIXING_ADDRS_ANALYSIS: str = "fixing_addrs_analysis"
    ADDRESS_ANALYSIS: str = "address_analysis"

class Processed(FileNames):
    """Datasets generated by different stages of the workflow."""
    TAXPAYER_RECORDS: str = "taxpayer_records"
    PROPERTIES: str = "properties"
    PROPERTIES_RENTALS: str = "properties_rentals"
    BUS_FILINGS: str = "bus_filings"
    BUS_NAMES_ADDRS: str = "bus_names_addrs"
    PROPERTY_ADDRESSES: str = "property_addresses"
    CORPS: str = "corps"
    LLCS: str = "llcs"
    CLASS_CODES: str = "class_codes"

    VALIDATED_ADDRS: str = "validated_addrs"
    UNVALIDATED_ADDRS: str = "unvalidated_addrs"

    TAXPAYERS_BUS_MERGED: str = "taxpayers_bus_merged"
    TAXPAYERS_ADDR_MERGED: str = "taxpayers_addr_merged"
    BUS_NAMES_ADDRS_MERGED: str = "bus_names_addrs_merged"
    BUS_NAMES_ADDRS_SUBSETTED: str = "bus_names_addrs_subsetted"

    TAXPAYERS_MERGED: str = "taxpayers_merged"
    CORPS_MERGED: str = "corps_merged"
    LLCS_MERGED: str = "llcs_merged"

    TAXPAYERS_FIXED: str = "taxpayers_fixed"
    TAXPAYERS_SUBSETTED: str = "taxpayers_subsetted"
    TAXPAYERS_PREPPED: str = "taxpayers_prepped"
    CORPS_SUBSETTED: str = "corps_subsetted"
    LLCS_SUBSETTED: str = "llcs_subsetted"
    TAXPAYERS_STRING_MATCHED: str = "taxpayers_string_matched"
    TAXPAYERS_NETWORKED: str = "taxpayers_networked"

class SummaryStats(FileNames):
    """Summary statistics for each stage of the workflow."""
    pass

class Output(FileNames):
    """Final datasets."""
    NETWORK_CALCS: str = "network_calcs"
    RESEARCH_ENTITY_TYPES: str = "research_entity_types"
    RESEARCH_ENTITIES: str = "research_entities"
    VALIDATED_ADDRESSES: str = "validated_addresses"
    LLCS: str = "llcs"
    CORPS: str = "corps"
    ENTITY_FILINGS: str = "entity_filings"
    ENTITY_NAMES_ADDRESSES: str = "entity_names_addresses"
    ENTITY_TYPES: str = "entity_types"
    ENTITY_NAME_TYPES: str = "entity_name_types"
    ENTITY_ADDRESS_TYPES: str = "entity_address_types"
    NETWORKS: str = "networks"
    TAXPAYER_RECORDS: str = "taxpayer_records"
    PROPERTIES: str = "properties"
    PROPERTY_ADDRESSES: str = "property_addresses"
    DATASETS: str = "datasets"
